document.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"775\">")
document.write("<tr><td width=\"775\" colspan=\"3\"><img src=\"../images/spacer.gif\" width=\"775\"height=\"35\"></td></tr>")
document.write("<tr>")
document.write("<td align=\"right\" width=\"670\"><a href=\"#1\"><img src=\"../images/point02up.gif\" border=\"0\"></a></td>")
document.write("<td width=\"5\"><img src=\"../images/spacer.gif\"></td>")
document.write("<td width=\"100\"><div class=\"small\" align=\"left\"><a href=\"#1\">ページの先頭へ</a></div></td>")
document.write("</tr>")
document.write("<tr>")
document.write("<td align=\"right\" width=\"670\"><a href=\"#1\"><img src=\"../images/point03left.gif\" border=\"0\"></a></td>")
document.write("<td width=\"5\"><img src=\"../images/spacer.gif\"></td>")
document.write("<td width=\"100\"><div class=\"small\" align=\"left\"><a href=\"../index.html\" target=\"_self\">トップページに戻る</a></div></td>")
document.write("</tr>")
document.write("<tr><td width=\"775\" colspan=\"3\"><img src=\"../images/spacer.gif\" width=\"775\" height=\"35\"></td></tr>")
document.write("</table>")
